### ISSUE TITLE
DESIGNER'S GUIDE TO DPI 格式问题

### ISSUE THREAD

**Issue by zicai** [yeol/blog#2]
DESIGNER'S GUIDE TO DPI 这篇文章里有几处markdown 斜体相关的

*\* _星号里面的文字是斜体_ 

例如：23.5 \* 109约等于2560，因此原始屏幕分辨率就是2560 \* 1440px
会被展示为斜体：
23.5_109约等于2560，因此原始屏幕分辨率就是2560_1440px

如果你需要用*号表示乘号需要在星号两端加空格

**Comment by yeol** [comment]
谢谢反馈呀，已经修改了！
